# Generated by Django 2.1.7 on 2019-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start_date',
            field=models.DateField(),
        ),
    ]
